mkdir "%homedrive%%homepath%\kWall"
move "%~dp0firewall.py" "%homedrive%%homepath%\kWall"
move "%~dp0kWall.bat" "%homedrive%%homepath%\kWall"
move "%~dp0kwall.ico" "%homedrive%%homepath%\kWall"
move "%~dp0kWall.lnk" "%homedrive%%homepath%\kWall"
move "%~dp0kwall.png" "%homedrive%%homepath%\kWall"
move "%~dp0license.txt" "%homedrive%%homepath%\kWall"
move "%~dp0README.txt" "%homedrive%%homepath%\kWall"
move "%~dp0updateFirewall.lnk" "%homedrive%%homepath%\kWall"
copy "%~dp0kWall.lnk" "%homedrive%%homepath%\Desktop"
echo Set oWS = WScript.CreateObject("WScript.Shell") > "%temp%\shortcut.vbs"
echo sLinkFile = "%homedrive%%homepath%\Desktop\kWall.lnk" >> "%temp%\shortcut.vbs"
echo Set oLink = oWS.CreateShortcut(sLinkFile) >> "%temp%\shortcut.vbs"
echo oLink.TargetPath = "%homedrive%%homepath%\kWall\kWall.lnk" >> "%temp%\shortcut.vbs"
echo oLink.Save >> "%temp%\shortcut.vbs"
cscript /nologo "%temp%\shortcut.vbs"
del "%temp%\shortcut.vbs"